cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository/
    - target/

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository/"

stages:
  - test
  - build

#Codedelivery:
#  stage: test
#  tags:
#    - test
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy -DskipTests $MAVEN_OPTS
#    - echo "installing the package in local repository"
#  only :
#    - master
    
codebuild-DEVELOP:
  stage: build
  tags:
    - java
  script:
    - mvn $MAVEN_CLI_OPTS clean install -U -DskipTests 
